### PR TITLE
Donations Flow

### PR DESCRIPTION
**Pull request by devmount**
This change implements the complete donations flow on clicking the download link.

thunderbird_donation_flow

This flow contains 3 steps:

1. Selection of the currency and donation amount
2. Input of payment data
3. Transaction result

The flow always starts with step 1. Step 2 shows the donation amount and provides the possibility to go back to step 1 to change it. Step 3 shows either success which automatically starts the download or failure, which provides to possibility to start again on step 1.

Also a loading spinner indicates background processing when switching between steps.

Not in the scope of this PR but planned for the next changes:

- URLs for the links in the modal footer

### CODE REVIEW

**Comment by Alecaddd** [comment]
I'm having issue in building this locally. I get this error:
```
File "build-site.py", line 57, in <module>
    site.build_website()
  File "/home/alecaddd/Mozilla/thunderbird-website/builder.py", line 285, in build_website
    self.render()
  File "/home/alecaddd/Mozilla/thunderbird-website/builder.py", line 263, in render
    t.stream().dump(filepath)
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1313, in dump
    fp.writelines(iterable)
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1309, in <genexpr>
    iterable = (x.encode(encoding, errors) for x in self)
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1357, in __next__
    return self._next()
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1125, in generate
    yield self.environment.handle_exception()
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/alecaddd/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "website/404.html", line 5, in top-level template code
    {% extends "_includes/base-resp.html" %}
  File "website/_includes/base-resp.html", line 5, in top-level template code
    {% extends "_includes/bedrock/base-resp.html" %}
  File "website/_includes/bedrock/base-resp.html", line 56, in top-level template code
    {% block site_header %}
  File "website/_includes/base-resp.html", line 62, in block "site_header"
    {% include '_includes/donate-modal.html' %}
  File "website/_includes/donate-modal.html", line 43, in top-level template code
    data-symbol="{{ vals.symbol.decode('utf-8') }}"
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'decode'
```

What am I doing wrong?

**Comment by devmount** [comment]
@Alecaddd Seems like you are using Python 3, afaik you need to use Python 2...

**Comment by Sancus** [comment]
It's supposed to work in both, but this branch doesn't really do that right now. I'll try to kill Python2 tomorrow, I just keep getting distracted by other things...

**Comment by devmount** [comment]
@Sancus Were you able to fix this Python issue?

**Comment by devmount** [comment]
@MelissaAutumn Any reason for throwing away my work without merging? No hard feelings, just curious 😅

**Comment by MelissaAutumn** [comment]
@devmount Hey there! Your work will mostly live on over at #356. We're going with a different donation provider, that has some restrictions/side effects on what we can pass along to it. So some stuff may change on the form, but I've tried to keep it pretty in-tact.

The deletion of thundernest:new and re-creation was due to a rebase gone terribly wrong on my end. Apologies for the confusion there. 😅

**Comment by devmount** [comment]
I see, thank you Mel for the explanation and for your work on this!

**Comment by Sancus** [comment]
> @MelissaAutumn Any reason for throwing away my work without merging? No hard feelings, just curious 😅

Just to add some information here, Mozilla Foundation is changing their donation stack completely, so the code we worked on for braintree is no longer going to be used. It's unfortunate, but the new stack makes thing so much easier that it's actually going to end up faster to complete it this way.

Thanks for your work on this anyhow, entirely my fault it was delayed so long :)

**Pull request closed without merging**
