### PR TITLE
Removed mention of Earlybird.

### PR DESCRIPTION
**Pull request by ryanleesipes**
Can continue to make improvements, but for now removing mention to Earlybird.

### CODE REVIEW

**Comment by Sancus** [comment]
Looks fine, do you want to add the link @wsmwk requested?

**Comment by ryanleesipes** [comment]
Yes, I'm trying to determine where to implement it. Any ideas?

**Comment by ryanleesipes** [comment]
Alright, I turned "Provide Feedback" into a link.

**Comment by Sancus** [comment]
Once the link is changed like I specified above, this can be merged.

**Comment by ryanleesipes** [comment]
@Sancus, fair point, this has been updated accordingly.

**Comment by ryanleesipes** [comment]
Thank you @Sancus!

**Pull request merged**
