### PR TITLE
Add 102 what's new page

### PR DESCRIPTION
**Pull request by micahilbery**
This is mostly a copy paste of the 91 what's new page with the content updated for 102. I'm open to explore greater changes but wanted to get this out there asap for translations.

### CODE REVIEW

**Comment by micahilbery** [comment]
Screenshot 2022-06-14 at 17-37-54 New in Thunderbird 102

**Comment by Alecaddd** [comment]
This looks very good.
The majority of the screenshots look very good, but I think we should have primarily Windows screenshots, at least for the header image. Our larger audience is on Windows, so visual familiarity and recognition is important.

**Comment by wsmwk** [comment]
two thumbs up

**Comment by ryanleesipes** [comment]
Looks good. Can you review @Sancus - or, even better, submit it for localization before review (if that's possible?)

**Review by ryanleesipes — COMMENTED** [review]
I agree that Windows screenshots would be good.

**Comment by Sancus** [comment]
I merged this and pushed the strings out to l10n in the interest of speed. Please do still update the screenshots in a separate PR.

**Pull request merged**
