### PR TITLE
Updated Daily start page with new icons.

### PR DESCRIPTION
**Pull request by ryanleesipes**
Also slightly different wording on the page.

### CODE REVIEW

**Comment by wsmwk** [comment]
But not live?  (I'm not seeing a change)

**Comment by Sancus** [comment]
@ryanleesipes Shouldn't the Get Involved section link to the new get involved page rather than the wiki?

**Comment by Sancus** [comment]
Other than that, looks good, r+. Let me know if you want to change that URL or if not I'll merge it as-is.

**Comment by Sancus** [comment]
https://start.thunderbird.net/en-US/daily/ This is now live.

**Pull request merged**
