### PR TITLE
Add Mastodon link to website footer.

### PR DESCRIPTION
**Pull request by freaktechnik**
This adds the mastodon account to the social media accounts in the footer, linking it with `rel="me"`, which will mark the website link on the mastodon account's profile as verified, thus making it easily visible that this is a public account.

What's not quite clear to me is how to handle the mastodon icon licensing. I got it from their press kit (in the footer of https://joinmastodon.org/) which didn't contain a license, but [wikicommons has it](https://commons.wikimedia.org/wiki/File:Mastodon_Logotype_(Simple).svg) marked as GPL-3.0.

Is there anything needed to make the strings translatable?

Screenshot 2022-05-05 at 10-53-33 Thunderbird — Make Email Easier

### CODE REVIEW

**Review by Sancus — CHANGES_REQUESTED** [review]
Put strings you want translated in the python gettext function like so:
`{{ _('Your String Goes Here.') }}`

**Comment by freaktechnik** [comment]
Ok, should I also give the other profile links a l10n treatment?

**Comment by Sancus** [comment]
Sure, feel free. Thanks!

**Comment by Sancus** [comment]
> No clue if the Thunderbird website actually uses it (or what for), but this repo contains Fontawesome files. It has a Mastodon icon as well:
> 
> https://fontawesome.com/icons/mastodon?s=brands

That's only used on the start page.

**Pull request merged**
