### PR TITLE
New home page

### PR DESCRIPTION
**Pull request by micahilbery**
Things still needed:
- [ ] links for "See Compatibility", "open source", "Mozilla"
- [ ] Download buttons in nav, header, and "Free Your Inbox" section

### CODE REVIEW

**Comment by micahilbery** [comment]
Screenshot 2023-07-10 at 00-27-55

**Comment by ryanleesipes** [comment]
On links:

Let's kill "See Compatibility" for now (comment it out or something). "Open Source" can link to this page: https://en.wikipedia.org/wiki/Open-source_software

Mozilla can link to https://mozilla.org

**Comment by ryanleesipes** [comment]
Perfect, thank you @micahilbery

**Comment by Sancus** [comment]
I'm going to merge this as-is so I can get started on translations, please do a followup.

**Pull request merged**
