### PR TITLE
Change daily download button to red, to match daily logo

### PR DESCRIPTION
**Pull request by jobisoft**
The beta download button matches the color of the beta logo. This pull request changes the color for the daily download button to match the daily logo, instead of being black:

grafik

### CODE REVIEW

**Comment by Sancus** [comment]
@Alecaddd This seem reasonable to you? Red is kinda scary for a button color, but then Dailies are kinda scary ;)

**Comment by Sancus** [comment]
I don't get why the bot modified this. What the heck???

**Comment by jobisoft** [comment]
Well, that bot is stupid. It saw your change and forced my master branch to be re-aligned with upstream, removing my commit and therefore removing my change in this pr. I have to create a dedicated branch for this pr in my repo. Will do that, then close this pr and reopen a new one.

**Comment by jobisoft** [comment]
Ok, I was able to resolve it.

**Comment by jobisoft** [comment]
Ok, I closed this PR and re-created it as https://github.com/thundernest/thunderbird-website/pull/273 but this time from a dedicated branch.

**Pull request closed without merging**
